### ISSUE TITLE
How do I install on embedded platforms

### ISSUE THREAD

**Issue by 1juewang** [w111liang222/lidar-slam-detection#24]
When I run tools/scripts/start_system.sh on the embedded platform, the following error is displayed
The File "/ usr/lib/python3.8 multiprocessing/process. Py", line 315, in _bootstrap
self.run()
The File "/ usr/lib/python3.8 multiprocessing/process. Py", line 108, in the run
self._target(*self._args, **self._kwargs)
File "web_backend/server.py", line 17, in perception_main
from module.perception import Perception
File "/root/lidar-slam-detection/module/perception.py", line 8, in <module>
import calibration.calibration
File "/root/lidar-slam-detection/calibration/calibration.py", line 4, in <module>
from sensor_driver.common_lib.cpp_utils import (
File "/root/lidar-slam-detection/sensor_driver/common_lib/cpp_utils.py", line 1, in <module>
import cpp_utils_ext
ModuleNotFoundError: No module named 'cpp_utils_ext'
Traceback (most recent call last):
File "web_backend/server.py", line 36, in <module>
from perception_server import PerceptionServer
File "/root/lidar-slam-detection/web_backend/perception_server.py", line 8, in <module>
from message_server import MessageServer
File "/root/lidar-slam-detection/web_backend/message_server.py", line 7, in <module>
from zerocm import ZCM
ImportError: dynamic module does not define module export function (PyInit_zerocm)
Is that something I didn't install

**Comment by w111liang222** [comment]
hi,
please use the tools/scripts/install_dependency.sh to install the zcm

**Comment by 1juewang** [comment]
Hello, thank you, but there doesn't seem to be a way to do it on an embedded platform yet.

I started to try something new. I installed ubuntu on my computer so that he could use my gpu, but there were still some problems in the running process.

Unlike the non-GPU version, the gpu version does not have any reaction and return value after running, and can only see the page but not operate after opening the website. Why?

**Comment by 1juewang** [comment]
![Uploading _cgi-bin_mmwebwx-bin_webwxgetmsgimg &MsgID=3559314865110347884&skey=@crypt_6b4263ba_ba9aec0f053006a5048ae5ac9b8e9c73&mmweb_appid=wx_webfilehelper.jpeg…]()
