### ISSUE TITLE
无法调用显卡加速1.3.1

### ISSUE THREAD

**Issue by zhu2900000** [w111liang222/lidar-slam-detection#31]
你好，我用的1.3.1版本，切换到目标检测模式后，可输出结果，但是好像没有用到显卡，检测帧率很低（速度慢），请问应该怎么调试以下，我的docker用的gpu版本

![Screenshot from 2024-05-27 16-33-53](https://github.com/w111liang222/lidar-slam-detection/assets/36877360/b8569fbc-ca87-48ba-9895-88d4f4530027)

un server python script
dpkg-query: no packages found matching nvidia-l4t-core
Running on board: IPC, machine: x86_64, jetpack: 20.04
2024-05-27 08:39:01,478[26853:26853][       infer.py: 23] image object detection is deactived
2024-05-27 08:39:01,490[26853:26853][module_manager.py: 47] pipeline: Source connect to Detect
2024-05-27 08:39:01,491[26853:26853][module_manager.py: 47] pipeline: Detect connect to Sink
2024-05-27 08:39:01,491[26853:26853][module_manager.py: 71] start to setup module: Detect
2024-05-27 08:39:01,506[26853:26853][object_filter.py: 25] class mapping: {'vehicle': 1, 'pedestrian': 2, 'cyclist': 3, 'traffic_cone': 4}
2024-05-27 08:39:01,506[26853:26853][module_manager.py: 73] setup module: Detect, done
2024-05-27 08:39:01,507[26853:26853][module_manager.py: 71] start to setup module: Sink
2024-05-27 08:39:01,513[26853:26853][module_manager.py: 73] setup module: Sink, done
2024-05-27 08:39:01,514[26853:26853][module_manager.py: 71] start to setup module: Source
2024-05-27 08:39:01,514[26874:26874][sink_template.py: 58] deamon UdpSink starts
2024-05-27 08:39:01,523[26853:26853][player_data_manager.py:135] player have 201 frames, duration 19.971323 s
/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:65: UserWarning: Specified provider 'OpenVINOExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  warnings.warn(
 * Serving Flask app 'module.source.player_data_manager'
 * Debug mode: off
2024-05-27 08:39:01,724[26853:26853][source_manager.py: 35] Source, start to setup: lidar
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:38000
Press CTRL+C to quit
2024-05-27 08:39:01.738[26853:26853][lidar_driver_wrapper.cpp:34] lidar 0:Ouster-OS1-64 open success
2024-05-27 08:39:01.738[26853:26853][lidar_driver_wrapper.cpp:46] set lidar 0:Ouster-OS1-64 external parameter [-0.03368380293250084, -0.660768985748291, 1.7658969163894653, 177.67449951171875, 135.47140502929688, -177.0221710205078]
2024-05-27 08:39:01.738[26853:26853][lidar_driver_wrapper.cpp:58] set lidar 0:Ouster-OS1-64 range filter [-72.0, -72.0, -2.0, 72.0, 72.0, 4.0]
2024-05-27 08:39:01.738[26853:26853][lidar_driver_wrapper.cpp:70] set lidar 0:Ouster-OS1-64 exclude [-2.13, -2.01, -5.0, 2.92, 0.5, 5.0]
2024-05-27 08:39:01.745[26853:26853][lidar_driver_wrapper.cpp:34] lidar 1:Ouster-OS1-128 open success
2024-05-27 08:39:01.745[26853:26853][lidar_driver_wrapper.cpp:46] set lidar 1:Ouster-OS1-128 external parameter [0.0, 0.0, 1.88961923122406, 179.99972534179688, 179.9855194091797, -177.86497497558594]
2024-05-27 08:39:01.745[26853:26853][lidar_driver_wrapper.cpp:58] set lidar 1:Ouster-OS1-128 range filter [-72.0, -72.0, -2.0, 72.0, 72.0, 4.0]
2024-05-27 08:39:01.745[26853:26853][lidar_driver_wrapper.cpp:70] set lidar 1:Ouster-OS1-128 exclude [-3.37, -3.02, -4.15, 3.16, 2.33, 4.7]
2024-05-27 08:39:01.751[26853:26853][lidar_driver_wrapper.cpp:34] lidar 2:Ouster-OS1-64 open success
2024-05-27 08:39:01.751[26853:26853][lidar_driver_wrapper.cpp:46] set lidar 2:Ouster-OS1-64 external parameter [-0.09995567798614502, 0.6768492460250854, 1.7785784006118774, 1.0974562168121338, -44.20530319213867, 2.35439395904541]
2024-05-27 08:39:01.751[26853:26853][lidar_driver_wrapper.cpp:58] set lidar 2:Ouster-OS1-64 range filter [-72.0, -72.0, -2.0, 72.0, 72.0, 4.0]
2024-05-27 08:39:01.751[26853:26853][lidar_driver_wrapper.cpp:70] set lidar 2:Ouster-OS1-64 exclude [-3.37, -3.14, -4.92, 3.16, 1.44, 4.58]
2024-05-27 08:39:01,751[26853:26853][source_manager.py: 38] Source, setup: lidar, done
2024-05-27 08:39:01,751[26853:26853][source_manager.py: 35] Source, start to setup: camera
2024-05-27 08:39:01,807[26853:26853][camera_data_manager.py:207] camera 0, try cap: souphttpsrc timeout=0 location=http://127.0.0.1:38000/v1/camera/0 ! jpegparse ! jpegdec ! video/x-raw  ! videoscale ! video/x-raw,width=1920,height=1080  ! videoconvert ! video/x-raw,width=1920,height=1080,format=I420 ! tee name=t
    t. ! queue ! jpegenc ! shmsink socket-path=/tmp/camera_jpeg_0 sync=false
    t. ! queue ! appsink sync=false 
127.0.0.1 - - [27/May/2024 08:39:01] "GET /v1/camera/0 HTTP/1.1" 200 -
[ WARN:0@0.925] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
2024-05-27 08:39:01,911[26853:26853][camera_data_manager.py:217] camera 0 open success
2024-05-27 08:39:01,911[26853:26853][camera_data_manager.py:207] camera 1, try cap: souphttpsrc timeout=0 location=http://127.0.0.1:38000/v1/camera/1 ! jpegparse ! jpegdec ! video/x-raw  ! videoscale ! video/x-raw,width=1920,height=1080  ! videoconvert ! video/x-raw,width=1920,height=1080,format=I420 ! tee name=t
    t. ! queue ! jpegenc ! shmsink socket-path=/tmp/camera_jpeg_1 sync=false
    t. ! queue ! appsink sync=false 
127.0.0.1 - - [27/May/2024 08:39:01] "GET /v1/camera/1 HTTP/1.1" 200 -
[ WARN:0@0.979] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
2024-05-27 08:39:01,965[26853:26853][camera_data_manager.py:217] camera 1 open success
2024-05-27 08:39:01,965[26853:26853][camera_data_manager.py:207] camera 2, try cap: souphttpsrc timeout=0 location=http://127.0.0.1:38000/v1/camera/2 ! jpegparse ! jpegdec ! video/x-raw  ! videoscale ! video/x-raw,width=1920,height=1080  ! videoconvert ! video/x-raw,width=1920,height=1080,format=I420 ! tee name=t
    t. ! queue ! jpegenc ! shmsink socket-path=/tmp/camera_jpeg_2 sync=false
    t. ! queue ! appsink sync=false 
127.0.0.1 - - [27/May/2024 08:39:04] "GET /v1/camera/2 HTTP/1.1" 200 -
[ WARN:0@3.389] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
2024-05-27 08:39:04,374[26853:26853][camera_data_manager.py:217] camera 2 open success
2024-05-27 08:39:04,374[26853:26853][camera_data_manager.py:207] camera 3, try cap: souphttpsrc timeout=0 location=http://127.0.0.1:38000/v1/camera/3 ! jpegparse ! jpegdec ! video/x-raw  ! videoscale ! video/x-raw,width=1920,height=1080  ! videoconvert ! video/x-raw,width=1920,height=1080,format=I420 ! tee name=t
    t. ! queue ! jpegenc ! shmsink socket-path=/tmp/camera_jpeg_3 sync=false
    t. ! queue ! appsink sync=false 
127.0.0.1 - - [27/May/2024 08:39:04] "GET /v1/camera/3 HTTP/1.1" 200 -
[ WARN:0@3.442] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
2024-05-27 08:39:04,427[26853:26853][camera_data_manager.py:217] camera 3 open success
2024-05-27 08:39:04,428[26853:26853][source_manager.py: 38] Source, setup: camera, done
2024-05-27 08:39:04,428[26853:26853][source_manager.py: 35] Source, start to setup: radar
2024-05-27 08:39:04,428[26853:26853][source_manager.py: 38] Source, setup: radar, done
2024-05-27 08:39:04,428[26853:26853][source_manager.py: 35] Source, start to setup: ins
2024-05-27 08:39:04.428[26853:26853][ins_driver_wrapper.cpp:19] ins open success
2024-05-27 08:39:04.428[26853:26853][ins_driver_wrapper.cpp:34] set ins external parameter [0.09695542603731155, 1.2899638414382935, -0.11553408205509186, 87.35172271728516, -0.02054435946047306, -0.8822724223136902]
2024-05-27 08:39:04.429[26853:26853][ins_driver_wrapper.cpp:43] ins start success
2024-05-27 08:39:04.429[26853:26952][ins_driver.cpp:317] start ins com receving, device /dev/ttyUSB0
2024-05-27 08:39:04.429[26853:26951][ins_driver.cpp:278] start ins udp receving, port 9888
2024-05-27 08:39:04,429[26853:26853][source_manager.py: 38] Source, setup: ins, done
2024-05-27 08:39:04.429[26853:26953][ins_driver.cpp:378] start ins gps receving
2024-05-27 08:39:04,429[26853:26853][module_manager.py: 73] setup module: Source, done
2024-05-27 08:39:04.429[26853:26953][ins_driver.cpp:381] No GPSD running
2024-05-27 08:39:04,430[26853:26954][manager_template.py: 80] Detect, FPS: 0.2
2024-05-27 08:39:04,431[26853:26956][data_manager_template.py: 57] Camera: 0: acquire_loop start
2024-05-27 08:39:04,431[26853:26958][data_manager_template.py: 57] Camera: 1: acquire_loop start
2024-05-27 08:39:04,432[26853:26853][  perception.py: 34] start success
2024-05-27 08:39:04,432[26853:26959][data_manager_template.py: 57] Camera: 2: acquire_loop start
2024-05-27 08:39:04,433[26853:26960][data_manager_template.py: 57] Camera: 3: acquire_loop start
[ WARN:1@3.455] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ WARN:2@3.461] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ WARN:3@3.463] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ WARN:4@3.493] global /tmp/opencv-4.5.5/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
2024-05-27 08:39:04,481[26853:26955][manager_template.py: 80] Source, FPS: 0.2
2024-05-27 08:39:04,568[26853:26853][   http_sink.py: 92] http query FPS: 0.2
2024-05-27 08:39:04,568[26853:26853][   http_sink.py: 98] http client connect
2024-05-27 08:39:04,569[26853:26984][   http_sink.py: 72] http sink process loop start
2024-05-27 08:39:05,112[26853:26853][   http_sink.py: 92] http query FPS: 1.0
2024-05-27 08:39:05,396[26853:26955][manager_template.py: 80] Source, FPS: 0.6
2024-05-27 08:39:05,474[26853:26957][module_manager.py:116] system status Running, running thread/process information:
2024-05-27 08:39:05,474[26853:26957][module_manager.py:120] Thread  26853:Perception daemon False ident 0x7f77608ca0c0
2024-05-27 08:39:05,475[26853:26957][module_manager.py:120] Thread  26954:Detect     daemon True ident 0x7f76d2ffd700
2024-05-27 08:39:05,475[26853:26957][module_manager.py:120] Thread  26955:Source     daemon True ident 0x7f76d27fc700
2024-05-27 08:39:05,475[26853:26957][module_manager.py:120] Thread  26956:Py-C0      daemon True ident 0x7f76d1ffb700
2024-05-27 08:39:05,475[26853:26957][module_manager.py:120] Thread  26958:Py-C1      daemon True ident 0x7f76d0ff9700
2024-05-27 08:39:05,475[26853:26957][module_manager.py:120] Thread  26959:Py-C2      daemon True ident 0x7f76affff700
2024-05-27 08:39:05,475[26853:26957][module_manager.py:120] Thread  26960:Py-C3      daemon True ident 0x7f76af7fe700
2024-05-27 08:39:05,476[26853:26957][module_manager.py:120] Thread  26961:zerorpc    daemon True ident 0x7f76aeffd700
2024-05-27 08:39:05,476[26853:26957][module_manager.py:120] Thread  26976:Py-J0      daemon True ident 0x7f76ae7fc700
2024-05-27 08:39:05,476[26853:26957][module_manager.py:120] Thread  26977:Py-J1      daemon True ident 0x7f7663fff700
2024-05-27 08:39:05,476[26853:26957][module_manager.py:120] Thread  26978:Py-J2      daemon True ident 0x7f76637fe700
2024-05-27 08:39:05,476[26853:26957][module_manager.py:120] Thread  26979:Py-J3      daemon True ident 0x7f7662ffd700
2024-05-27 08:39:05,477[26853:26957][module_manager.py:120] Thread  26984:HttpSink   daemon True ident 0x7f7643fff700
2024-05-27 08:39:05,824[26871:26871][  infer_base.py: 99] lidarDet inference time is: 414.6 ms
2024-05-27 08:39:06,018[26873:26873][detect_template.py: 63] tracker process time is: 186.8 ms
2024-05-27 08:39:06,038[26853:26954][manager_template.py: 80] Detect, FPS: 0.4
2024-05-27 08:39:06,228[26871:26871][  infer_base.py: 99] lidarDet inference time is: 381.2 ms
2024-05-27 08:39:06,257[26853:26954][manager_template.py: 80] Detect, FPS: 2.5
jpeg encoder, worker 0 loop starts
jpeg encoder, worker 1 loop starts
jpeg encoder, worker 2 loop starts
jpeg encoder, worker 3 loop starts
jpeg encoder, worker 4 loop starts
jpeg encoder, worker 5 loop starts
2024-05-27 08:39:06,261[26853:26955][manager_template.py: 80] Source, FPS: 5.4
2024-05-27 08:39:06,616[26871:26871][  infer_base.py: 99] lidarDet inference time is: 362.6 ms
2024-05-27 08:39:06,631[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 4.9
2024-05-27 08:39:06,645[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 6.1
2024-05-27 08:39:07,064[26871:26871][  infer_base.py: 99] lidarDet inference time is: 426.9 ms
2024-05-27 08:39:07,429[26871:26871][  infer_base.py: 99] lidarDet inference time is: 358.4 ms
2024-05-27 08:39:07,908[26853:26853][   http_sink.py: 92] http query FPS: 0.7
2024-05-27 08:39:07,910[26853:26955][manager_template.py: 80] Source, FPS: 3.0
2024-05-27 08:39:07,915[26853:26954][manager_template.py: 80] Detect, FPS: 1.5
2024-05-27 08:39:07,955[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 3.4
2024-05-27 08:39:07,956[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 5.0
2024-05-27 08:39:08,339[26871:26871][  infer_base.py: 99] lidarDet inference time is: 414.1 ms
2024-05-27 08:39:07,960[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 5.2
2024-05-27 08:39:08,368[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 2.7
2024-05-27 08:39:08,371[26853:26955][manager_template.py: 80] Source, FPS: 2.6
2024-05-27 08:39:08,799[26871:26871][  infer_base.py: 99] lidarDet inference time is: 448.1 ms
2024-05-27 08:39:08,806[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 3.1
2024-05-27 08:39:08,809[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 2.5
2024-05-27 08:39:08,832[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 2.3
2024-05-27 08:39:08,835[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 3.2
2024-05-27 08:39:08,843[26853:26955][manager_template.py: 80] Source, FPS: 2.4
2024-05-27 08:39:09,174[26871:26871][  infer_base.py: 99] lidarDet inference time is: 349.9 ms
2024-05-27 08:39:09,570[26871:26871][  infer_base.py: 99] lidarDet inference time is: 387.9 ms
2024-05-27 08:39:09,598[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 2.2
2024-05-27 08:39:09,601[26853:26853][   http_sink.py: 92] http query FPS: 0.6
2024-05-27 08:39:09,604[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 1.8
2024-05-27 08:39:09,609[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 1.9
2024-05-27 08:39:09,616[26853:26955][manager_template.py: 80] Source, FPS: 1.8
2024-05-27 08:39:09,638[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 5.5
2024-05-27 08:39:09,678[26853:26853][module_manager.py: 91] system is started
2024-05-27 08:39:09,711[26853:26955][manager_template.py: 80] Source, FPS: 6.2
2024-05-27 08:39:09,856[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 5.1
2024-05-27 08:39:09,957[26853:26955][manager_template.py: 80] Source, FPS: 5.1
2024-05-27 08:39:10,050[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 7.4
2024-05-27 08:39:10,050[26871:26871][  infer_base.py: 99] lidarDet inference time is: 426.7 ms
2024-05-27 08:39:10,053[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 5.1
2024-05-27 08:39:10,056[26853:26955][manager_template.py: 80] Source, FPS: 7.6
2024-05-27 08:39:10,231[26853:26955][manager_template.py: 80] Source, FPS: 6.7
2024-05-27 08:39:10,318[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 6.9
2024-05-27 08:39:10,335[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 7.8
2024-05-27 08:39:10,455[26871:26871][  infer_base.py: 99] lidarDet inference time is: 381.5 ms
2024-05-27 08:39:10,485[26853:26955][manager_template.py: 80] Source, FPS: 5.3
2024-05-27 08:39:10,598[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 5.8
2024-05-27 08:39:10,600[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 5.2
2024-05-27 08:39:10,627[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 5.6
2024-05-27 08:39:10,631[26853:26853][   http_sink.py: 92] http query FPS: 0.8
2024-05-27 08:39:10,689[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 6.1
2024-05-27 08:39:10,872[26871:26871][  infer_base.py: 99] lidarDet inference time is: 392.7 ms
2024-05-27 08:39:10,898[26853:26955][manager_template.py: 80] Source, FPS: 3.9
2024-05-27 08:39:10,919[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 4.5
2024-05-27 08:39:10,920[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 5.2
2024-05-27 08:39:10,921[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 4.2
2024-05-27 08:39:10,921[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 4.5
2024-05-27 08:39:11,031[26853:26853][   http_sink.py: 92] http query FPS: 1.6
2024-05-27 08:39:11,281[26871:26871][  infer_base.py: 99] lidarDet inference time is: 383.5 ms
2024-05-27 08:39:11,307[26853:26955][manager_template.py: 80] Source, FPS: 3.2
2024-05-27 08:39:11,330[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 3.5
2024-05-27 08:39:11,725[26871:26871][  infer_base.py: 99] lidarDet inference time is: 432.8 ms
2024-05-27 08:39:11,750[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 2.8
2024-05-27 08:39:11,755[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 2.7
2024-05-27 08:39:12,109[26871:26871][  infer_base.py: 99] lidarDet inference time is: 364.7 ms
2024-05-27 08:39:12,131[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 3.0
2024-05-27 08:39:12,148[26853:26955][manager_template.py: 80] Source, FPS: 2.2
2024-05-27 08:39:12,497[26871:26871][  infer_base.py: 99] lidarDet inference time is: 377.0 ms
2024-05-27 08:39:12,518[26853:26853][   http_sink.py: 92] http query FPS: 1.2
2024-05-27 08:39:12,529[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 2.8
2024-05-27 08:39:12,531[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 2.1
2024-05-27 08:39:12,531[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 2.0
2024-05-27 08:39:12,538[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 2.1
2024-05-27 08:39:12,965[26871:26871][  infer_base.py: 99] lidarDet inference time is: 451.8 ms
2024-05-27 08:39:12,990[26853:26955][manager_template.py: 80] Source, FPS: 1.7
2024-05-27 08:39:13,326[26871:26871][  infer_base.py: 99] lidarDet inference time is: 355.6 ms
2024-05-27 08:39:13,327[26853:26954][manager_template.py: 80] Detect, FPS: 7.1
2024-05-27 08:39:13,351[26853:26956][data_manager_template.py: 66] Camera: 0, acquire FPS: 2.0
2024-05-27 08:39:13,366[26853:26959][data_manager_template.py: 66] Camera: 2, acquire FPS: 1.6
2024-05-27 08:39:13,367[26853:26958][data_manager_template.py: 66] Camera: 1, acquire FPS: 1.6
^CProcess UdpSink:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/module/sink/sink_template.py", line 63, in _run
    data_dict = self.input_queue.get(block=True, timeout=0.1)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/sensor_inference/infer_base.py", line 94, in _infer_thread
    result = self.process(data_dict)
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/sensor_inference/lidar_infer.py", line 102, in process
    cls_preds, box_preds, label_preds = pointpillar_infer(self.engine, lidar_data)
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/sensor_inference/lidar_infer.py", line 53, in pointpillar_infer
    return pointpillar_infer_onnx(engine, input_tuple)
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/sensor_inference/lidar_infer.py", line 38, in pointpillar_infer_onnx
    cls_preds, box_preds, label_preds = engine.run(None, {'voxel_features': input_tuple[0],
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
KeyboardInterrupt
KeyboardInterrupt
2024-05-27T08:39:13Z
Process fusion:
2024-05-27 08:39:13,764[26853:26960][data_manager_template.py: 66] Camera: 3, acquire FPS: 1.5
Process tracker:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/sensor_fusion/fusion.py", line 220, in _run_thread
    super()._run_thread()
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/module/detect/detect_template.py", line 52, in _run_thread
    input_dict = self.input_queue.get(block=True, timeout=0.1)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/sensor_fusion/tracker.py", line 81, in _run_thread
    super()._run_thread()
  File "/home/znqc/work/new/1.3.1/lidar-slam-detection/module/detect/detect_template.py", line 52, in _run_thread
    input_dict = self.input_queue.get(block=True, timeout=0.1)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
2024-05-27T08:39:13Z
2024-05-27 08:39:13,764[26853:26954][manager_template.py: 80] Detect, FPS: 4.7
Traceback (most recent call last):
  File "web_backend/server.py", line 100, in <module>
    http_server.serve_forever()
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 400, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
KeyboardInterrupt
2024-05-27 08:39:13,777[26853:26955][manager_template.py: 80] Source, FPS: 1.5
2024-05-27 08:39:13,781[26853:26959][camera_data_manager.py:228] camera 2, get invalid data
2024-05-27 08:39:13,781[26853:26960][camera_data_manager.py:228] camera 3, get invalid data
2024-05-27 08:39:13,781[26853:26958][camera_data_manager.py:228] camera 1, get invalid data
2024-05-27 08:39:13,781[26853:26956][camera_data_manager.py:228] camera 0, get invalid data
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "web_backend/server.py", line 25, in perception_main
    start_perception_server(perception, "ipc:///tmp/perception")
  File "web_backend/server.py", line 14, in start_perception_server
    s.run()
  File "/usr/local/lib/python3.8/dist-packages/zerorpc/core.py", line 176, in run
    self._acceptor_task.get()
  File "src/gevent/greenlet.py", line 826, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 814, in gevent._gevent_cgreenlet.Greenlet.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch

**Comment by w111liang222** [comment]
v1.3.1版本目标检测在x86上目前只能运行在CPU上(基于openvino)，需要自行将onnx文件转换成tensorrt来调用显卡加速

**Comment by zhu2900000** [comment]
> v1.3.1版本目标检测在x86上目前只能运行在CPU上(基于openvino)，需要自行将onnx文件转换成tensorrt来调用显卡加速
谢谢，master分支的支持吗？

**Comment by zhu2900000** [comment]
> v1.3.1版本目标检测在x86上目前只能运行在CPU上(基于openvino)，需要自行将onnx文件转换成tensorrt来调用显卡加速
谢谢，master分支的支持吗？
@w111liang222

**Comment by w111liang222** [comment]
master分支是支持的，但对显卡有要求，需要SM80以上架构的，你的tesla P4好像不满足。。

**Comment by zhu2900000** [comment]
> master分支是支持的，但对显卡有要求，需要SM80以上架构的，你的tesla P4好像不满足。。

谢谢，如果我想让master分支支持p4显卡，应该如何修改代码，有建议吗？

**Comment by zhu2900000** [comment]
> master分支是支持的，但对显卡有要求，需要SM80以上架构的，你的tesla P4好像不满足。。

谢谢，如果我想让master分支支持p4显卡，应该如何修改代码，有建议吗？

**Comment by zhu2900000** [comment]
> master分支是支持的，但对显卡有要求，需要SM80以上架构的，你的tesla P4好像不满足。。

谢谢，如果我想让master分支支持p4显卡，应该如何修改代码，有建议吗？
